spring:

  application:
    name: depart-provider

  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        username: nacos
        password: nacos

        shared-configs[0]:
          data_id: tent-db.yml
          refresh: true

        extension-configs[0]:
          data_id: log.yml
          refresh: true

  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:tent-db.yml
      - optional:nacos:log.yml